name: CD-PIPELINE-DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: techiesmatch

    steps:
    - name: Deploy with DORA Metrics
      env:
        PUSHGATEWAY_URL: http://18.171.107.108:9091
        JOB_NAME: CD_FE_DEV
        ENV: DEV
        SERVICE: FE
        TYPE: CD
      run: |
        START_TIME=$(date +%s)

        # >>>>> Actual Job Starts >>>>>
        
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
        set -e  # Exit if any command fails
        set -x  # Print commands for debugging

        # Navigate to the project directory
        cd fe/dev

        # Ensure the correct branch is checked out
        git checkout dev

        # Remove untracked files and reset any local changes
        git reset --hard HEAD
        git clean -fd

        # Pull the latest changes
        git pull origin dev

        # Install dependencies
        pnpm install

        # Export environment variables
        export NEXT_PUBLIC_BACKEND_URL="${{ secrets.NEXT_PUBLIC_BACKEND_URL }}"
        export NEXT_PUBLIC_PHOTO_URL="${{ secrets.NEXT_PUBLIC_PHOTO_URL_DEV }}"
        export NEXT_PUBLIC_WS_URL="${{ secrets.NEXT_PUBLIC_WS_URL_DEV }}"

        # Build the project
        pnpm run build

        # Restart the application using PM2
        pm2 restart techiesmatch-dev || pm2 start "pnpm run start" --name "techiesmatch-dev"

        EOF

        # <<<<< Actual Job Ends <<<<<

        JOB_EXIT_CODE=$?
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))

        # Push metrics
        if [ $JOB_EXIT_CODE -eq 0 ]; then
          SUCCESS=1
          echo "Deployment succeeded. Pushing DF metric..."
          echo "github_actions_deployments_total{env=\"$ENV\",service=\"$SERVICE\",type=\"$TYPE\"} 1" | \
            curl --data-binary @- $PUSHGATEWAY_URL/metrics/job/$JOB_NAME
        else
          SUCCESS=0
          echo "Deployment failed. Pushing CFR metric..."
          echo "github_failed_deployments_total{env=\"$ENV\",service=\"$SERVICE\",type=\"$TYPE\"} 1" | \
            curl --data-binary @- $PUSHGATEWAY_URL/metrics/job/$JOB_NAME
        fi

        echo "Pushing LTC metric..."
        echo "github_commit_to_deploy_seconds{env=\"$ENV\",service=\"$SERVICE\",type=\"$TYPE\"} ${DURATION}" | \
          curl --data-binary @- $PUSHGATEWAY_URL/metrics/job/$JOB_NAME


          echo "Pushing MTTR metric..."
          echo "github_incident_recovery_seconds{env=\"$ENV\",service=\"$SERVICE\",type=\"$TYPE\"} ${DURATION}" | \
            curl --data-binary @- $PUSHGATEWAY_URL/metrics/job/$JOB_NAME

        exit $JOB_EXIT_CODE