name: CI-Pipeline-DEV

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: techiesmatch
    env:
      PUSHGATEWAY_URL: http://<server-ip>:9091  
      JOB_NAME: CI_FE_DEV
      ENV: DEV
      SERVICE: FE
      TYPE: CI

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js with pnpm caching
      uses: actions/setup-node@v3
      with:
        node-version: '20.13.1'
        cache: 'pnpm'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Cache pnpm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install Dependencies (Faster)
      run: pnpm install --frozen-lockfile --prefer-offline

    - name: Run Linting & Build + Push DORA Metrics
      shell: bash
      env:
        PUSHGATEWAY_URL: http://18.171.107.108:9091 
        JOB_NAME: CI_FE_DEV
        ENV: DEV
        SERVICE: FE
        TYPE: CI
      run: |
        START_TIME=$(date +%s)

        # >>>>> Actual Job Starts >>>>>

        pnpm run lint || true &
        pnpm run build
        
        JOB_EXIT_CODE=$?
        # <<<<< Actual Job Ends <<<<<

        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))

        # Determine success
        if [ $JOB_EXIT_CODE -eq 0 ]; then
          echo "✅ Build succeeded."
          echo "github_actions_deployments_total{env=\"$ENV\",service=\"$SERVICE\",type=\"$TYPE\"} 1" | \
            curl --data-binary @- $PUSHGATEWAY_URL/metrics/job/$JOB_NAME
        else
          echo "❌ Build failed."
          echo "github_failed_deployments_total{env=\"$ENV\",service=\"$SERVICE\",type=\"$TYPE\"} 1" | \
            curl --data-binary @- $PUSHGATEWAY_URL/metrics/job/$JOB_NAME
        fi

        # Lead Time for Changes (LTC)
        echo "github_commit_to_deploy_seconds{env=\"$ENV\",service=\"$SERVICE\",type=\"$TYPE\"} ${DURATION}" | \
          curl --data-binary @- $PUSHGATEWAY_URL/metrics/job/$JOB_NAME

        # Mean Time to Restore (MTTR)
          echo "github_incident_recovery_seconds{env=\"$ENV\",service=\"$SERVICE\",type=\"$TYPE\"} ${DURATION}" | \
            curl --data-binary @- $PUSHGATEWAY_URL/metrics/job/$JOB_NAME

        exit $JOB_EXIT_CODE
