global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['https://techie.love']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox_ssl'
    metrics_path: /probe
    params:
      module: [http_with_ssl]  # This is the SSL-checking module
    static_configs:
      - targets: ['https://techie.love']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'github_actions_metrics'
    static_configs:
      - targets: ['pushgateway:9091']


# TO SCRAPE MULTIPLE DOMAINS 
#   - job_name: 'blackbox_ssl'
#     metrics_path: /probe
#     params:
#       module: [http_with_ssl]
#     static_configs:
#       - targets:
#           - https://yourserver.com
#           - https://anotherdomain.com
#           - https://yetanotherdomain.com
